[Account account_1701171588_0]
Provider=google
Identity=banoni.bro@gmail.com
PresentationIdentity=banoni.bro@gmail.com
MailEnabled=true
CalendarEnabled=true
ContactsEnabled=true
PhotosEnabled=true
FilesEnabled=true
PrintersEnabled=true

[Account account_1701171873_1]
Provider=ubuntusso
Identity=banoni.bro@gmail.com
PresentationIdentity=banoni.bro@gmail.com
